openapi: 3.0.0
servers:
  - url: https://shopapi.activeants.nl
    description: Default server
info:
  description: |
    The Active Ants Shop API was made to replace the old Novulo Webservice. Much of the old
    functionality has been kept, but there have been quite a few changes. One of them is the conversion
    to JSON. This document will cover all different calls you can perform in as much detail as possible. For
    each operation we will define which fields are needed to use the API, and provide you with the URL
    to use for your JSON requests.
  version: 2.0.1
  title: Active Ants Shop API
paths:
  '/v2/rma/add':
    post:
      tags:
        - rma
      summary: Creates a new RMA
      description: Creates a new return merchandise authorisation (RMA)
      operationId: addRma
      responses:
        200: 
          description: Success
          content:
            application/json:
              schema:
                type: string
                example: 1434980924
        401:
          description: Invalid RMA
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Rma'
components:
  schemas:
    Rma:
      type: object
      properties:
        shippingId:
          description: Reference to the shipment that contained the products when they were shipped to the customers address
          type: string
          example: 1899222311
        remark:
          description: A free text remark to add to the return merchandise authorisation.
          type: string
          example: Thanks for shipping out so fast! Unfortunately the items do not fit me.
        items:
          description: An array or items to be returned, each item may originate from a different shipment
          type: array
          minItems: 1
          maxItems: 99
          items:
            type: object
            properties:
              shippingItemId:
                description: Reference to the line-item of the shipment the particular product was returned on. This is used to look up the SKU among other things.
                type: string
                example: 4358838211
              quantity:
                description: The number of the particular item to return, this must be 1 or higher
                type: integer
                minimum: 1
              reasonId:
                description: The id of the reason for returning this item. 
                type: integer


